name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: pnpm/action-setup@v6
        name: Install pnpm
        with:
          version: 11
          cache: true
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Zip
        run: pnpm zip
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: extension
          path: extension.zip

  deploy:
    needs: build
    environment: publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: extension
      - name: Create release
        uses: release-drafter/release-drafter@v7
        with:
          config-name: templates/release-template.yml
      - name: Publish Chrome Extension
        uses: wdzeng/chrome-extension@src-v2.0.0
        with:
          publisher-id: 4ec42777-23b5-48b7-9868-2aaee3915064
          extension-id: dkcipnihgbegpammhgkobheodoknplma
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          zip-path: extension.zip
          action: upload
